config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ## -----
  ## DEVISE
  ## -----

  devise_for :admin_users, skip: [:registrations]
  authenticate :admin_user do
    mount GoodJob::Engine => "/good_job"
  end

  devise_for :users, skip: [:registrations], controllers: {
    sessions: "users/sessions"
  }
  devise_scope :user do
    # we've disabled registrations to avoid sign ups, but we still want editable users
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"

    get "magic-authentication", to: "users/sessions#redirect_from_magic_token"
    namespace :users, as: :user do
      resource :session, only: %i[new create destroy]
      resources :session_codes, only: %i[new create]
      resource :unsubscribe, only: %i[new create]
    end
  end

  devise_for :conservateurs, only: %i[sessions passwords]
  devise_scope :conservateur do
    # we've disabled registrations to avoid sign ups, but we still want editable conservateurs
    get "conservateurs/edit" => "devise/registrations#edit", :as => "edit_conservateur_registration"
  end

  devise_for :recenseurs, only: %i[sessions], controllers: {
    sessions: "recenseurs/sessions"
  }
  devise_scope :recenseur do
    namespace :recenseurs, as: :recenseur do
      resource :session, only: %i[new create destroy]
      resources :session_codes, only: %i[new create]
      resource  :optout, only: :destroy do
        get "(:token)", action: :new, as: :new
      end
      resource :registration, only: [:show, :edit, :update, :destroy]
    end
  end

  direct :annuaire_service_public do |commune|
    if commune.is_a? Commune
      "https://www.service-public.fr/particuliers/recherche?keyword=mairie+#{commune.nom}+#{commune.departement.nom}"
    else
      "https://lannuaire.service-public.fr/navigation/mairie"
    end
  end

  ## ------
  ## PUBLIC
  ## ------

  root "pages#home"
  controller :pages do
    get :stats
    get :conditions
    get :mentions_legales
    get :confidentialite
    get "comment-ca-marche", action: :aide, as: :aide
    get "guide-de-recensement", action: :guide, as: :guide
    get :pdf, to: redirect("guide-de-recensement")
    get :admin
    get :plan
    get :declaration_accessibilite
    get :schema_pluriannuel_accessibilite
    get :accueil_conservateurs
  end
  get "campaigns.ics", to: "pages#campaigns_ics", as: :campaigns_ics
  resources :fiches, only: %i[index show]
  get "/presse", to: "presse#index", as: :presse
  get "/presse/:id", to: "presse#show", as: :article_presse
  resources :survey_votes, only: %w[new create]

  resources :communes, only: :show
  resources :objets, only: [:index, :show]
  resources :contenus, only: %i[show], controller: "content_blobs", as: "content_blobs"

  ## --------
  ## COMMUNES
  ## --------

  resources :communes, module: :communes, only: [] do
    controller :pages do
      get :premiere_visite
    end
    resource :completion, only: %i[new create show]
    resources :objets, only: %i[index show] do
      resources :recensements, only: %i[create edit update destroy] do
        resources :photos, only: %i[create destroy], controller: "recensement_photos"
      end
    end
    resource :dossier, only: [:show]
    resources :campaign_recipients, only: [:update]
    resources :messages, only: %i[index new create] do
      resources :email_attachments, only: [:show]
    end
    resource :user, only: [:update]
    resources :recenseurs, only: [:index, :create, :show] do
      resources :access, only: [:update, :destroy], as: :recenseur_access, controller: :recenseur_accesses
    end
  end

  ## --------
  ## RECENSEURS
  ## --------

  namespace :recenseurs do
    controller :pages do
      get :premiere_visite
      put :premiere_visite, action: :after_premiere_visite, as: :after_premiere_visite
    end
    resources :communes, only: %i[index show] do
      resource :completion, only: %i[new create show]
      resources :objets, only: %i[index show] do
        resources :recensements, only: %i[create edit update destroy] do
          resources :photos, only: %i[create destroy], controller: "recensement_photos"
        end
      end
      resource :dossier, only: [:show]
      # resources :campaign_recipients, only: [:update]
      resources :messages, only: %i[index new create] do
        resources :email_attachments, only: [:show]
      end
    end
  end

  ## -------------
  ## CONSERVATEURS
  ## -------------

  namespace :conservateurs do
    resources :departements, only: %i[index show] do
      get :activite, on: :collection, action: :activite_des_departements
      get :carte, on: :member
      get :activite, on: :member
      resources :campaigns, only: %i[new]
    end
    resources :communes, only: [:show] do
      collection do
        post :autocomplete
      end
      resources :messages, only: %i[index new create] do
        resources :email_attachments, only: [:show]
      end
      resource :dossier, only: :show
      get :historique, as: :historique, to: "dossiers#historique"
      resources :bordereaux, only: %i[index create show]
      resource :deleted_recensements, only: [:show]
    end
    resources :objets, only: [] do
      resources :recensements, only: [] do
        resource :analyse, only: %i[edit update]
      end
    end
    resources :dossiers, only: [] do
      resource :accept, only: %i[new create update destroy]
    end
    resources :campaigns, except: %i[new index] do
      get :edit_recipients
      patch :update_recipients
      patch :update_status
      get :mail_previews
      resources :recipients, controller: "campaign_recipients", only: :update do
        get :mail_preview
      end
    end
    resources :recenseurs do
      resources :accesses, only: [:new, :create, :update], as: :recenseur_access, controller: :recenseur_accesses
    end
    resource :conservateur, only: [:update]
    resources :visits, only: [:index]
    resources :fiches, only: :index
    resources :attachments, only: %i[create update destroy]
  end

  ## -----
  ## ADMIN
  ## -----

  namespace :admin do
    resources :communes, only: %i[index show] do
      post :session_code, on: :member
    end
    resources :conservateurs do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
    end
    resources :dossiers, only: [:show]
    resources :users, only: %i[] do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
    end
    resources :recenseurs do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
      resources :accesses, only: [:show, :new, :create, :update], as: :recenseur_access, controller: :recenseur_accesses
    end
    get "/session_codes(/:offset)", to: "session_codes#index", as: :session_codes
    resources :campaigns do
      get :edit_recipients
      patch :update_recipients
      patch :update_status
      get :mail_previews
      if Rails.configuration.x.environment_specific_name != "production"
        post :force_start
        post :force_step_up
      end
      resources :recipients, controller: "campaign_recipients", only: :update do
        get :mail_preview
      end
      resources :emails, controller: "campaign_emails", only: [] do
        get :redirect_to_sib_preview
      end
    end
    resources :admin_comments, only: %i[create destroy], controller: "comments"
    namespace :exports do
      resources :memoire, except: :edit
      controller :mpp do
        get :deplaces
        get :manquants
      end
    end
    resources :attachments, only: [:destroy] do
      post :rotate
      put :exportable
    end
    resources :messages, only: [:create] do
      resources :email_attachments, only: [:show]
    end
    resources :mail_previews, only: [:index] do
      get "/:mailer/:email", on: :collection, action: :show, as: :preview
    end
    resources :admin_users
  end

  # -----
  # API
  # -----

  namespace :api do
    namespace :v1 do
      resources :inbound_emails, only: [:create]
    end
  end

  # --------------
  # HEALTH & DEBUG
  # --------------

  get "health/raise_on_purpose", to: "health#raise_on_purpose"
  get "health/js_error", to: "health#js_error"
  get "health/slow_image", to: "health#slow_image" if Rails.env.development?
end

# rubocop:enable Metrics/BlockLength

app/models/completion.rb
# frozen_string_literal: true

class Completion
  attr_reader :dossier

  delegate :commune, :notes_commune, to: :dossier

  def initialize(dossier:)
    @dossier = dossier
  end

  def create!(user:, notes_commune:)
    return false unless dossier.submit!(notes_commune:)

    SendMattermostNotificationJob.perform_async("commune_completed", { "commune_id" => commune.id })
    UserMailer.with(user_id: user.id, commune_id: commune.id).commune_completed_email.deliver_later
    true
  end
end

app/controllers/communes/completions_controller.rb
# frozen_string_literal: true

module Communes
  class CompletionsController < BaseController
    before_action :set_dossier_completion_and_authorize
    before_action :set_objets
    before_action :set_missing_photos, only: %i[new create]

    def show
      render "shared/completions/show"
    end

    def new
      render "shared/completions/new"
    end

    def create
      if @dossier_completion.create!(**dossier_completion_params)
        redirect_to commune_objets_path(@commune), notice: "Le recensement de votre commune est terminé !"
      else
        render :new, status: :unprocessable_content
      end
    end

    protected

    def set_dossier_completion_and_authorize
      @dossier_completion = DossierCompletion.new(dossier: @dossier)
      authorize(@dossier_completion)
    end

    def set_objets
      @objets = @dossier.objets
        .includes(:commune, recensement: %i[photos_attachments photos_blobs])
    end

    def set_missing_photos
      @missing_photos = @dossier.recensements.any?(&:missing_photos?)
    end

    def dossier_completion_params
      params.require(:dossier_completion).permit(:notes_commune, :recenseur).to_h.symbolize_keys
        .merge(user: current_user)
    end

    def active_nav_links = %w[Recensement]
  end
end

app/controllers/recenseurs/completions_controller.rb
# frozen_string_literal: true

module Recenseurs
  class CompletionsController < BaseController
    before_action :set_commune, :set_dossier
    before_action :set_dossier_completion_and_authorize
    before_action :set_objets
    before_action :set_missing_photos, only: %i[new create]

    def show
      render "shared/completions/show"
    end

    def new
      render "shared/completions/new"
    end

    def create
      if @dossier_completion.create!(**dossier_completion_params)
        redirect_to recenseurs_commune_objets_path(@commune), notice: "Le recensement de votre commune est terminé !"
      else
        render :new, status: :unprocessable_content
      end
    end

    protected

    def set_dossier_completion_and_authorize
      @dossier_completion = DossierCompletion.new(dossier: @dossier)
      authorize(@dossier_completion)
    end

    def set_objets
      @objets = @dossier.objets
        .includes(:commune, recensement: %i[photos_attachments photos_blobs])
    end

    def set_missing_photos
      @missing_photos = @dossier.recensements.any?(&:missing_photos?)
    end

    def dossier_completion_params
      params.require(:dossier_completion).permit(:notes_commune, :recenseur).to_h.symbolize_keys
        .merge(user: current_recenseur)
    end

    def active_nav_links = %w[Recensement]
  end
end

app/views/shared/completions/_status.html.haml
- if commune.inactive?
  %h2.co-text--blue
    = t("communes.objets.index.n_objets_a_recenser", count:)
  = render "recensements/etapes"
- elsif commune.can_complete?
  %h2.co-text--blue
    = t("communes.objets.index.tous_les_objets_recenses")
  = render "communes/objets/complete_callout", dossier:, commune:
- elsif commune.started?
  %h2.co-text--blue
    = t("communes.objets.index..n_objets_restants_a_recenser", count: commune.objets.without_completed_recensements.count)
  = render "recensements/etapes"
- elsif commune.completed? && dossier.submitted?
  - if commune.messages.from_conservateur.blank?
    = render "communes/objets/submitted_callout", commune:
- elsif commune.completed? && dossier.accepted?
  = render "communes/objets/accepted_callout", dossier:

app/views/shared/completions/_summary.html.haml
.fr-table.co-recensement-completion-summary
  %table
    %thead
      %tr
        %th Objet
        %th Localisation
        %th Recensable
        %th État de l’objet
        %th Sécurisation
        %th Photos
    %tbody
      - objets.each do |objet|
        - recensement = objet.recensement
        - presenter = RecensementPresenter.new(recensement)
        - palissy_photo_presenter = recensement.objet.palissy_photos_presenters.first
        %tr
          %td
            %div
              %div
                - if palissy_photo_presenter
                  %img.co--width-max-100{alt: palissy_photo_presenter.alt, src: palissy_photo_presenter.url}
                - else
                  = vite_image_tag "images/illustrations/photo-manquante.png", alt: "Photo manquante"
              %div
                - objet_path = current_recenseur ? recenseurs_commune_objet_path(objet.commune, objet) : commune_objet_path(objet.commune, objet)
                = link_to truncate(recensement.objet.nom, length: 30), objet_path
          %td= presenter.localisation
          %td= presenter.recensable
          %td
            = render Conservateurs::AnalyseOverrideComponent.new recensement:, recensement_presenter: presenter, original_attribute_name: :etat_sanitaire
          %td
            = render Conservateurs::AnalyseOverrideComponent.new recensement:, recensement_presenter: presenter, original_attribute_name: :securisation
          %td
            - if recensement.missing_photos?
              = badge("warning") { "Aucune photo" }
            - elsif recensement.photos.any?
              %div
                = recensement.photos.count
                photo#{recensement.photos.count > 1 ? 's' : ""}
              .co-recensement-photos{tabindex: "0"}
                - recensement.photos.each_with_index.map do |photo, index|
                  %div= image_tag photo.variant(:medium), alt: "Recensement #{index + 1}"

app/views/shared/completions/new.html.haml
- content_for(:head_title) { "Finalisation du recensement de #{@commune.nom}" }
%main#contenu.fr-container.fr-pb-8w
  - objets_path = current_recenseur ? recenseurs_commune_objets_path(@commune) : commune_objets_path(@commune)
  = render"shared/breadcrumbs",
    links: [["Accueil", root_path], ["Objets de #{@commune.nom}", objets_path]], current_page_label: "Finalisation"

  - if @commune.errors.any?
    .fr-grid-row
      .fr-col-md-6
        .fr-alert.fr-alert--error.fr-mb-6w
          %p
            Votre recensement n'a pas pu être confirmé :
          %ul
            - @commune.errors.attribute_names.each do |attribute|
              %li= @commune.errors.messages_for(attribute).first

  %h1 Finalisation du recensement de #{@commune.nom}

  .co-readable
    %p
      Veuillez vérifier la complétion et l'exactitude de vos recensements avant de les transmettre aux conservateurs de votre département.

  = render "shared/completions/summary", objets: @objets

  - completion_path = current_recenseur ? recenseurs_commune_completion_path(@commune) : commune_completion_path(@commune)
  = form_for @dossier_completion,
    as: :dossier_completion,
    url: completion_path,
    method: :post,
    builder: FormBuilderDsfr,
    data: (@missing_photos ? { turbo_confirm: "Un recensement d'objet sans photo vous sera probablement renvoyé par les conservateurs. Êtes-vous sûr de vouloir valider votre recensement en l'état ?" } : {}) do |f|
    .fr-grid-row.fr-grid-row--gutters
      .fr-col-md-9.fr-mb-2w
        .fr-input-group
          = f.label :notes_commune, t("activerecord.attributes.dossier.interface_communes.notes_commune")
          = f.text_area :notes_commune
        .fr-input-group
          = f.label :recenseur do
            = t("activerecord.attributes.dossier.recenseur")
            %span.fr-hint-text= t("activerecord.attributes.dossier.recenseur_hint_html", confidentialite_path:)
          = f.text_area :recenseur
    .actions
      = f.submit "Je valide le recensement", name: nil

app/views/shared/completions/show.html.haml
- content_for(:head_title) { "Recensements de #{@commune.nom}" }
%main#contenu.fr-container.fr-pt-2w.fr-pb-8w
  - objets_path = current_recenseur ? recenseurs_commune_objets_path(@commune) : commune_objets_path(@commune)
  = render "shared/breadcrumbs",  links: [["Accueil", root_path], ["Objets de #{@commune.nom}", objets_path]],  current_page_label: "Données envoyées"

  %h1 Recensement de #{@commune.nom}

  .co-readable
    %p Merci d'avoir participé et validé le recensement des objets de votre commune ! Un conservateur a été prévenu et reviendra vers vous.

  = render "shared/completions/summary", objets: @objets

  .fr-grid-row.fr-grid-row--gutters
    .fr-col-md-6.fr-mb-4w
      - if @dossier.notes_commune.present?
        = t("activerecord.attributes.dossier.notes_commune")
        = blockquote(@dossier.notes_commune)
      - else
        %p.co-text--italic Aucun commentaire à destination des conservateurs
      - if @dossier.recenseur.present?
        = t("activerecord.attributes.dossier.recenseur")
        = blockquote(@dossier.recenseur)