config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ## -----
  ## DEVISE
  ## -----

  devise_for :admin_users, skip: [:registrations]
  authenticate :admin_user do
    mount GoodJob::Engine => "/good_job"
  end

  devise_for :users, skip: [:registrations], controllers: {
    sessions: "users/sessions"
  }
  devise_scope :user do
    # we've disabled registrations to avoid sign ups, but we still want editable users
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"

    get "magic-authentication", to: "users/sessions#redirect_from_magic_token"
    namespace :users, as: :user do
      resource :session, only: %i[new create destroy]
      resources :session_codes, only: %i[new create]
      resource :unsubscribe, only: %i[new create]
    end
  end

  devise_for :conservateurs, only: %i[sessions passwords]
  devise_scope :conservateur do
    # we've disabled registrations to avoid sign ups, but we still want editable conservateurs
    get "conservateurs/edit" => "devise/registrations#edit", :as => "edit_conservateur_registration"
  end

  devise_for :recenseurs, only: %i[sessions], controllers: {
    sessions: "recenseurs/sessions"
  }
  devise_scope :recenseur do
    namespace :recenseurs, as: :recenseur do
      resource :session, only: %i[new create destroy]
      resources :session_codes, only: %i[new create]
      resource  :optout, only: :destroy do
        get "(:token)", action: :new, as: :new
      end
      resource :registration, only: [:show, :edit, :update, :destroy]
    end
  end

  direct :annuaire_service_public do |commune|
    if commune.is_a? Commune
      "https://www.service-public.fr/particuliers/recherche?keyword=mairie+#{commune.nom}+#{commune.departement.nom}"
    else
      "https://lannuaire.service-public.fr/navigation/mairie"
    end
  end

  ## ------
  ## PUBLIC
  ## ------

  root "pages#home"
  controller :pages do
    get :stats
    get :conditions
    get :mentions_legales
    get :confidentialite
    get "comment-ca-marche", action: :aide, as: :aide
    get "guide-de-recensement", action: :guide, as: :guide
    get :pdf, to: redirect("guide-de-recensement")
    get :admin
    get :plan
    get :declaration_accessibilite
    get :schema_pluriannuel_accessibilite
    get :accueil_conservateurs
  end
  get "campaigns.ics", to: "pages#campaigns_ics", as: :campaigns_ics
  resources :fiches, only: %i[index show]
  get "/presse", to: "presse#index", as: :presse
  get "/presse/:id", to: "presse#show", as: :article_presse
  resources :survey_votes, only: %w[new create]

  resources :communes, only: :show
  resources :objets, only: [:index, :show]
  resources :contenus, only: %i[show], controller: "content_blobs", as: "content_blobs"

  ## --------
  ## COMMUNES
  ## --------

  resources :communes, module: :communes, only: [] do
    controller :pages do
      get :premiere_visite
    end
    resource :completion, only: %i[new create show]
    resources :objets, only: %i[index show] do
      resources :recensements, only: %i[create edit update destroy] do
        resources :photos, only: %i[create destroy], controller: "recensement_photos"
      end
    end
    resource :dossier, only: [:show]
    resources :campaign_recipients, only: [:update]
    resources :messages, only: %i[index new create] do
      resources :email_attachments, only: [:show]
    end
    resource :user, only: [:update]
    resources :recenseurs, only: [:index, :create, :show] do
      resources :access, only: [:update, :destroy], as: :recenseur_access, controller: :recenseur_accesses
    end
  end

  ## --------
  ## RECENSEURS
  ## --------

  namespace :recenseurs do
    controller :pages do
      get :premiere_visite
      put :premiere_visite, action: :after_premiere_visite, as: :after_premiere_visite
    end
    resources :communes, only: %i[index show] do
      resource :completion, only: %i[new create show]
      resources :objets, only: %i[index show] do
        resources :recensements, only: %i[create edit update destroy] do
          resources :photos, only: %i[create destroy], controller: "recensement_photos"
        end
      end
      resource :dossier, only: [:show]
      # resources :campaign_recipients, only: [:update]
      resources :messages, only: %i[index new create] do
        resources :email_attachments, only: [:show]
      end
    end
  end

  ## -------------
  ## CONSERVATEURS
  ## -------------

  namespace :conservateurs do
    resources :departements, only: %i[index show] do
      get :activite, on: :collection, action: :activite_des_departements
      get :carte, on: :member
      get :activite, on: :member
      resources :campaigns, only: %i[new]
    end
    resources :communes, only: [:show] do
      collection do
        post :autocomplete
      end
      resources :messages, only: %i[index new create] do
        resources :email_attachments, only: [:show]
      end
      resource :dossier, only: :show
      get :historique, as: :historique, to: "dossiers#historique"
      resources :bordereaux, only: %i[index create show]
      resource :deleted_recensements, only: [:show]
    end
    resources :objets, only: [] do
      resources :recensements, only: [] do
        resource :analyse, only: %i[edit update]
      end
    end
    resources :dossiers, only: [] do
      resource :accept, only: %i[new create update destroy]
    end
    resources :campaigns, except: %i[new index] do
      get :edit_recipients
      patch :update_recipients
      patch :update_status
      get :mail_previews
      resources :recipients, controller: "campaign_recipients", only: :update do
        get :mail_preview
      end
    end
    resources :recenseurs do
      resources :accesses, only: [:new, :create, :update], as: :recenseur_access, controller: :recenseur_accesses
    end
    resource :conservateur, only: [:update]
    resources :visits, only: [:index]
    resources :fiches, only: :index
    resources :attachments, only: %i[create update destroy]
  end

  ## -----
  ## ADMIN
  ## -----

  namespace :admin do
    resources :communes, only: %i[index show] do
      post :session_code, on: :member
    end
    resources :conservateurs do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
    end
    resources :dossiers, only: [:show]
    resources :users, only: %i[] do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
    end
    resources :recenseurs do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
      resources :accesses, only: [:show, :new, :create, :update], as: :recenseur_access, controller: :recenseur_accesses
    end
    get "/session_codes(/:offset)", to: "session_codes#index", as: :session_codes
    resources :campaigns do
      get :edit_recipients
      patch :update_recipients
      patch :update_status
      get :mail_previews
      if Rails.configuration.x.environment_specific_name != "production"
        post :force_start
        post :force_step_up
      end
      resources :recipients, controller: "campaign_recipients", only: :update do
        get :mail_preview
      end
      resources :emails, controller: "campaign_emails", only: [] do
        get :redirect_to_sib_preview
      end
    end
    resources :admin_comments, only: %i[create destroy], controller: "comments"
    namespace :exports do
      resources :memoire, except: :edit
      controller :mpp do
        get :deplaces
        get :manquants
      end
    end
    resources :attachments, only: [:destroy] do
      post :rotate
      put :exportable
    end
    resources :messages, only: [:create] do
      resources :email_attachments, only: [:show]
    end
    resources :mail_previews, only: [:index] do
      get "/:mailer/:email", on: :collection, action: :show, as: :preview
    end
    resources :admin_users
  end

  # -----
  # API
  # -----

  namespace :api do
    namespace :v1 do
      resources :inbound_emails, only: [:create]
    end
  end

  # --------------
  # HEALTH & DEBUG
  # --------------

  get "health/raise_on_purpose", to: "health#raise_on_purpose"
  get "health/js_error", to: "health#js_error"
  get "health/slow_image", to: "health#slow_image" if Rails.env.development?
end

# rubocop:enable Metrics/BlockLength

app/controllers/admin/campaigns_controller.rb
# frozen_string_literal: true

module Admin
  class CampaignsController < BaseController
    include CampaignsControllerConcern

    def index
      @ransack = Campaign.includes(:departement).ransack(params[:q])
      @query_present = params[:q].present?
      @pagy, @campaigns = pagy(@ransack.result, items: 20)
    end

    def new
      @campaign = Campaign.new
    end

    def force_start
      set_campaign
      raise unless @campaign.can_force_start?

      update_dates_up_to "date_lancement"
      @campaign.update_columns status: "planned"
      enqueue_campaign_jobs
      redirect_to admin_campaign_path(@campaign), notice: "La campagne est en train de démarrer…"
    end

    def force_step_up
      set_campaign
      raise unless @campaign.can_force_step_up?

      next_step = @campaign.next_step
      update_dates_up_to("date_#{next_step}")
      enqueue_campaign_jobs
      redirect_to admin_campaign_path(@campaign), notice: "La campagne est en train de passer à l'étape #{next_step}…"
    end

    private

    def enqueue_campaign_jobs
      Campaigns::CronJob.perform_now
      Campaigns::RefreshCampaignStatsJob.set(wait: 10.minutes).perform_later(@campaign.id)
    end

    def search_params
      return {} if params[:campaign_search].blank?

      params.require(:campaign_search).permit(:departement_code, :status).to_h.symbolize_keys
    end

    def update_dates_up_to(up_to_date_field)
      dates_attributes =
        Campaign::DATE_FIELDS[0..Campaign::DATE_FIELDS.index(up_to_date_field)]
          .each_with_index.to_h do |date_field, index|
          weeks_ago = 5 - index
          date = (Time.zone.today - weeks_ago.weeks).monday
          [date_field, date]
        end
      @campaign.update_columns dates_attributes
    end

    def authorize_campaign = true
    def routes_prefix = :admin
    def after_destroy_path = admin_campaigns_path
    def active_nav_links = %w[Campagnes]
  end
end

app/controllers/conservateurs/campaigns_controller.rb
# frozen_string_literal: true

module Conservateurs
  class CampaignsController < BaseController
    include CampaignsControllerConcern

    # rubocop:disable Rails/LexicallyScopedActionFilter
    # Certaines actions sont définies dans le concern partagés par admins et conservateurs
    before_action :authorize_campaign, except: %i[new create]
    after_action :enqueue_admin_mail, only: %i[update_status]
    # rubocop:enable Rails/LexicallyScopedActionFilter

    def new
      @departement = Departement.find(params[:departement_id])
      @campaign = Campaign.new(departement: @departement)
      authorize(@campaign)

      defaults = @departement.campaigns.select(:sender_name, :nom_drac, :signature).last&.attributes
      defaults ||= {
        sender_name: current_conservateur.full_name,
        nom_drac: @departement.region,
        signature: [
          current_conservateur.full_name,
          nil,
          "conservateur en charge des monuments historiques",
          "DRAC #{@departement.region}"
        ].join("\n")
      }
      @campaign.assign_attributes(defaults)
    end

    private

    def enqueue_admin_mail
      return if @status_event != "plan" || !@success

      AdminMailer.campaign_planned(current_conservateur, @campaign).deliver_later
    end

    def routes_prefix = :conservateurs
    def after_destroy_path = conservateurs_departement_path @campaign.departement
    def authorize_campaign = authorize @campaign
    def active_nav_links = ["Mes départements", @departement.to_s]
  end
end

app/helpers/campaign_helper.rb
# frozen_string_literal: true

module CampaignHelper
  def campaign_status_badge(campaign)
    color = {
      "draft" => :warning,
      "planned" => :new,
      "ongoing" => :info,
      "finished" => :success
    }[campaign.status]
    text = I18n.t("activerecord.attributes.campaign.statuses.#{campaign.status}")
    tag.span text, class: "fr-badge fr-badge--sm fr-badge--#{color}"
  end

  def campaigns_statuses_options
    Campaign::STATUSES.map { [t("activerecord.attributes.campaign.statuses.#{_1}"), _1] }
  end

  def campaign_title(campaign)
    "#{campaign.departement.nom} #{campaign.date_lancement.strftime('%m/%Y')}"
  end

  def campaign_communes_statuses_line_chart_datasets(statuses_stats)
    nb_started = statuses_stats.fetch("construction", 0)
    nb_submitted = statuses_stats.fetch("submitted", 0)
    nb_accepted = statuses_stats.fetch("accepted", 0)
    nb_inactive = statuses_stats.fetch("total", 0) - (nb_started + nb_submitted + nb_accepted)
    [
      { label: "Inactive", data: [nb_inactive], backgroundColor: "rgb(254, 247, 218)" },
      { label: "En cours de recensement", data: [nb_started], backgroundColor: "rgb(252, 198, 58)" },
      { label: "Recensement terminé", data: [nb_submitted], backgroundColor: "rgb(192, 140, 101)" },
      { label: "Recensement examiné", data: [nb_accepted], backgroundColor: "rgb(149, 226, 87)" }
    ]
  end

  def campaign_objets_statuses_line_chart_datasets(objets_stats)
    nb_recensés = objets_stats.fetch("recensed", 0)
    nb_non_recensés = objets_stats.fetch("not_recensed", 0)
    [
      { label: "Pas encore recensé", data: [nb_non_recensés], backgroundColor: "rgb(254, 247, 218)" },
      { label: "Recensé", data: [nb_recensés], backgroundColor: "rgb(149, 226, 87)" }
    ]
  end
end

app/views/shared/campaigns/_badges.html.haml
= campaign_status_badge(campaign)
- if campaign.imported?
  %span.fr-badge.fr-badge--sm Importée
- if campaign.ongoing?
  %span.fr-badge.fr-badge--sm
    = t("campaigns.step_names.#{campaign.current_step}")

app/views/shared/campaigns/_edit_recipients_content.html.haml
%p.fr-mb-4w= "Liste des #{campaign.available_communes.load.size} communes abritant des objets <abbr title='Monuments Historiques'>MH</abbr> #{campaign.departement.dans_nom}.".html_safe

= form_for campaign, builder: FormBuilderDsfr, url: send("#{routes_prefix}_campaign_update_recipients_path", campaign), data: { controller: "multichecker" } do |f|
  %ul.fr-btns-group.fr-btns-group--icon-left.fr-btns-group--inline-md.fr-mb-4w
    %li
      %button.fr-btn.fr-btn--secondary.fr-btn--icon-left.fr-icon-check-line{"data-action" => "multichecker#checkAll"}
        Tout sélectionner
    %li
      %button.fr-btn.fr-btn--tertiary.fr-btn--icon-left.fr-icon-close-line{"data-action" => "multichecker#uncheckAll"}
        Tout désélectionner
    %li.fr-ml-auto
      %button.fr-btn.fr-btn--primary.fr-btn--icon-left.fr-icon-checkbox-circle-fill{type: :submit} Enregistrer la sélection

  %fieldset.fr-fieldset
    %legend.fr-sr-only
      Communes
    %input{type: :hidden, name: "campaign[commune_ids][]", value: "" }
    .fr-fieldset__element
      = render UnfoldComponent.new(max_height_px: 200, button_text: "Afficher toutes les communes…") do
        .co-columns-auto.co-columns-sm-2.co-columns-lg-3.fr-mx-0.w-100
          - campaign.available_communes.each do |commune|
            - disabled = commune.users_count.zero? || commune.dossier&.construction?
            - checked = !disabled && (communes_ids.include?(commune.id) || (communes_ids.empty? && !commune.dossier&.submitted?))
            - input_id = "campaign_commune_#{commune.id}"
            .fr-checkbox-group.fr-checkbox-group--sm.fr-mb-1w.co-break-avoid-column
              %input{type: :checkbox,
                name: "campaign[commune_ids][]",
                id: input_id,
                value: commune.id,
                checked:,
                "data-multichecker-target": :checkbox,
                disabled: }
              %label.fr-label{for: input_id}
                %span{title: (commune.nom.length > 25 ? commune.nom : nil)}= truncate(commune.nom, length: 25)
                - if commune.users_count.zero?
                  = badge(:warning, class: "fr-ml-auto", small: true) { "Pas d'email" }
                - else
                  = commune_statut_global_badge(commune, class: "fr-ml-auto", small: true)

  .fr-mt-4w.co-text--center
    %button.fr-btn.fr-btn--primary.fr-btn--icon-left.fr-icon-checkbox-circle-fill{type: :submit} Enregistrer la sélection

app/views/shared/campaigns/_form.html.haml
- if campaign.errors.any?
  .fr-alert.fr-alert--error.fr-mb-6w
    %p
      Votre campagne n'a pas pu être enregistrée :
    %ul
      - campaign.errors.attribute_names.each do |attribute|
        %li= campaign.errors.messages_for(attribute).first

= form_for [routes_prefix, campaign], builder: FormBuilderDsfr do |f|
  .fr-grid-row.fr-grid-row--gutters
    .fr-col-md-6
      %h2 Configuration
      .fr-input-group
        = f.label :departement_code
        = f.select :departement_code, Departement.order(:code).all.map { [_1.to_s, _1.code ] }, {}, disabled: campaign.persisted? || local_assigns[:departement_disabled]
        - if local_assigns[:departement_disabled]
          = f.hidden_field :departement_code
      .fr-input-group
        = f.label :sender_name do
          = t("activerecord.attributes.campaign.sender_name")
          %span.fr-hint-text
            C'est ce nom qui sera affiché dans les mails reçus par les communes.
            Les mails seront envoyés de "[nom émetteur] via Collectif Objets", avec l'adresse de la messagerie.
            Vous serez notifiés à chaque nouveau message de la commune dans la messagerie.
        = f.text_field :sender_name, placeholder: "Jeanne Dupont"
      .fr-input-group
        = f.label :nom_drac do
          = t("activerecord.attributes.campaign.nom_drac")
          %span.fr-hint-text
            Ce nom de DRAC sera utilisé dans des phrases comme "La DRAC Grand Est vous invite à participer…". Il ne faut pas inclure DRAC au début, seulement "Grand Est".
        = f.text_field :nom_drac, placeholder: "Grand Est"
      .fr-input-group
        = f.label :signature do
          = t("activerecord.attributes.campaign.signature")
          %span.fr-hint-text
            La signature sera utilisée dans le bas du mail. Elle peut faire entre 1 et 8 lignes.
        = f.text_area :signature, placeholder: "Jeanne Dupont\n\nConservatrice en charge des monuments historiques\nDRAC Rhône-Alpes, Châlons-sur-Saone, 10 rue de la république", rows: 4
    .fr-col-md-6
      %h2 Dates
      .fr-mb-2w{"data-controller" => "date-lancement"}
        - Campaign::DATE_FIELDS.each_with_index do |date_field, index|
          .fr-input-group
            = f.label date_field do
              = t("activerecord.attributes.campaign.#{date_field}")
              - if index.zero?
                %span.fr-hint-text Veuillez sélectionner un jour du lundi au vendredi.
            = f.date_field(                                     |
                date_field,                                     |
                class: "fr-input",                              |
                "data-date-lancement-target": :input,           |
                "data-action": "change->date-lancement#set"     |
              )                                                 |
  .fr-input-group.co-text--right.fr-mt-4w
    = f.submit campaign.persisted? ? "Sauvegarder" : "Créer la campagne"
    - if campaign.new_record?
      %p.co-text--italic
        Vous pourrez définir les communes à inclure dans cette campagne à l'étape suivante

app/views/shared/campaigns/_mail_previews_content.html.haml
= form_with url: send("#{routes_prefix}_campaign_mail_previews_path", campaign), method: :get, class: "fr-mr-md-2w", builder: FormBuilderDsfr do |f|
  .fr-input-group
    = f.label :commune_id, "Commune à prévisualiser"
    = f.collection_select :commune_id, campaign.communes, :id, :nom, { selected: recipient.commune_id }, class: "fr-select", data: { controller: "input-autosubmit", action: "input-autosubmit#submit" }
  .fr-input-group
    = f.submit "Prévisualiser le mail", name: nil, class: "fr-hidden"

- mail = CampaignV1Mailer.with(user: recipient.commune.user, commune: recipient.commune, campaign:).lancement_email
= render Conservateurs::MailIframeComponent.new mail:, display_headers: false, fit: true

app/views/shared/campaigns/_show_content.html.haml
- r = local_assigns[:routes_prefix]

- if campaign.errors.any?
  .fr-alert.fr-alert--error.fr-mb-6w
    %p
      %ul
        - campaign.errors.attribute_names.each do |attribute|
          %li= campaign.errors.messages_for(attribute).first

- if campaign.draft? && campaign.date_lancement > Time.zone.today
  = form_for [:admin, campaign], builder: FormBuilderDsfr, url: send("#{r}_campaign_update_status_path", campaign) do |f|
    = f.hidden_field :status_event, value: "plan"
    .fr-callout
      %p.fr-callout__text
        Cette campagne est en brouillon. Pour qu’elle démarre effectivement le #{l(campaign.date_lancement, format: :long_with_weekday)}, cliquez sur "Planifier la campagne". Vous pourrez repasser la campagne en brouillon si nécessaire, jusqu’à la date de lancement de campagne.
      = f.submit "Planifier la campagne"

- elsif campaign.planned? && campaign.date_lancement > Time.zone.today
  = form_for campaign, builder: FormBuilderDsfr, url: send("#{r}_campaign_update_status_path", campaign) do |f|
    = f.hidden_field :status_event, value: "return_to_draft"
    .fr-callout.fr-callout--brown-caramel
      %p.fr-callout__text
        Cette campagne est planifiée,
        = succeed "." do
          %b
            elle démarrera le #{l(campaign.date_lancement, format: :long_with_weekday)}
        %br/
        Si vous avez besoin de la modifier ou de l'annuler, vous pouvez la repasser en brouillon.
      = f.submit "Repasser en brouillon"

- if (campaign.ongoing? || campaign.finished?) && campaign.stats.present?
  = render "shared/campaigns/stats", stats: campaign.stats

.fr-grid-row.fr-grid-row--gutters.fr-mb-8w
  .fr-col-lg-6
    %h2 Configuration
    %div
      %b Nom de l'émetteur des mails :
      %span= campaign.sender_name.presence || "N/A"
    %div
      %b
        Nom de la DRAC en charge :
      %span= campaign.nom_drac.presence || "N/A"
    %div
      %b Signature des mails :
      - if campaign.signature.present?
        .co-white-space-pre-line.co-blockquote= campaign.signature
      - else
        %span N/A
    %ul.fr-btns-group.fr-btns-group--icon-left.fr-btns-group--inline-md.fr-mt-2w
      %li
        = button_to "Modifier la configuration", send("edit_#{r}_campaign_path", campaign), class: "fr-btn fr-btn--secondary fr-btn--icon-left fr-icon-pencil-line", method: :get, disabled: !campaign.draft?
      %li
        = button_to "Prévisualiser les messages", send("#{r}_campaign_mail_previews_path", campaign), method: :get, class: "fr-btn fr-btn--secondary fr-btn--icon-left fr-icon-eye-line fr-my-1w fr-mt-md-0", disabled: campaign.communes.empty?

  .fr-col-lg-6
    %h2 Dates
    %table
      %tbody
        - Campaign::DATE_FIELDS.each do |date_field|
          %tr
            %th.text-start.text-lg-end.w-50.w-md-25.w-lg-auto.fr-pr-2w
              = t("activerecord.attributes.campaign.#{date_field}")
            %td= l(campaign.send(date_field), format: :long_with_weekday)
        %tr
          %td{colspan: 2}
            %ul.fr-btns-group.fr-btns-group--icon-left.fr-btns-group--inline-md.fr-mt-2w
              %li
                = button_to "Modifier les dates", send("edit_#{r}_campaign_path", campaign), class: "fr-btn fr-btn--secondary fr-btn--icon-left fr-icon-calendar-2-line", method: :get, disabled: !campaign.draft?
              %li
                = button_to "Supprimer la campagne", send("#{r}_campaign_path", campaign), method: :delete, class: "fr-btn fr-btn--tertiary fr-btn--icon-left fr-icon-delete-line fr-my-1w fr-mt-md-0", disabled: !campaign.draft?, data: { turbo_confirm: "Êtes-vous sûr.e  de vouloir supprimer ce brouillon ? C'est irréversible." }

%h2 Communes destinataires
- if campaign.communes.any?
  %p
    La campagne concerne
    %b= Commune.human_attribute_name(:count, count: campaign.recipients.count)
    parmi les
    %b= Commune.human_attribute_name(:count, count: campaign.departement.communes_count)
    du département.

  - if (campaign.draft? || campaign.planned?) && campaign.communes_en_cours.load.any?
    = dsfr_alert(type: :warning, title: "Communes en cours d'examen", classes: "fr-mb-2w") do
      %p
        Attention, vous vous apprêtez à recontacter #{Commune.human_attribute_name(:count, count: campaign.communes_en_cours.size)} dont l’examen n'est pas terminé.
        %strong
          Les données saisies par ces communes seront perdues.
        %br
        Nous vous invitons à finaliser l'examen des communes suivantes avant de les inclure dans une nouvelle campagne&nbsp;:
        %br
        = "#{campaign.communes_en_cours.collect { |commune| link_to(commune.nom, conservateurs_commune_dossier_path(commune)) }.to_sentence.html_safe}."
  = render UnfoldComponent.new(max_height_px: 200, button_text: "Afficher toutes les communes…") do
    %ul.co-columns-auto.co-columns-sm-2.co-columns-lg-3.fr-mx-0
      - campaign.communes.include_statut_global.sort_by_nom.each do |commune|
        - url_commune = current_conservateur ? conservateurs_commune_path(commune) : admin_commune_path(commune)
        %li.co-position-relative.fr-enlarge-link.co-break-avoid-column
          .co-flex.co-flex--space-between
            = link_to commune.nom, url_commune, class: "fr-mr-auto"
            = commune_statut_global_badge(commune, small: true)
  - if excluded_communes.load.any?
    = render UnfoldComponent.new(max_height_px: 200, button_text: "Afficher toutes les communes exclues…") do
      %p
        %strong #{excluded_communes.size} communes exclues de la campagne &nbsp;:
      %ul.co-columns-auto.co-columns-sm-2.co-columns-lg-3.fr-mx-0
        - excluded_communes.include_statut_global.each do |commune|
          - url_commune = current_conservateur ? conservateurs_commune_path(commune) : admin_commune_path(commune)
          %li.co-position-relative.fr-enlarge-link.co-break-avoid-column
            .co-flex.co-flex--space-between
              = link_to commune.nom, url_commune
              - if commune.users_count.zero?
                = badge(:warning, class: "fr-ml-auto", small: true) { "Pas d'email" }
              - else
                = commune_statut_global_badge(commune, class: "fr-ml-auto", small: true)

- else
  %p
    Aucune commune parmi les
    %b= Commune.human_attribute_name(:count, count: campaign.departement.communes_count)
    du département n'a été sélectionnée.

= button_to campaign.communes.any? ? "Modifier les communes destinataires" : "Définir les communes destinataires", send("#{r}_campaign_edit_recipients_path", campaign), method: :get, class: "fr-btn fr-btn--secondary", disabled: !campaign.draft_or_planned?

app/views/shared/campaigns/_stats.html.haml
.fr-mb-4w
  %h2 Statistiques
  .fr-grid-row.fr-grid-row--gutters
    - if stats[:statuses].present? || stats[:objets].present?
      .fr-col-md-6
        - if stats[:statuses].present?
          %p
            Statut des #{@campaign.recipients_count} communes
          %canvas{data: { controller: "stacked-line-chart",
            datasets: campaign_communes_statuses_line_chart_datasets(stats[:statuses]).to_json,
            "unit-suffix": "commune(s)",
            "x-title": "nombre de communes"} }

      - if stats[:objets].present?
        .fr-col-md-6
          %p
            = stats[:objets][:total]
            objets à recenser

          %canvas{data: { controller: "stacked-line-chart",
            datasets: campaign_objets_statuses_line_chart_datasets(stats[:objets]).to_json,
            "unit-suffix": "objet(s)",
            "x-title": "nombre d’objets"} }

          - if stats[:objets][:recensements_with_photos_ratio].present?
            %p.fr-mt-2w
              = (stats[:objets][:recensements_with_photos_ratio] * 100).round
              \% des recensements ont des photos

app/views/shared/campaigns/mail_previews.html.haml
- title = "Prévisualisation des mails de lancement de la campagne #{campaign_title(@campaign)}"
- content_for(:head_title) { title }

%main#contenu.fr-container.fr-mb-8w
  = render "shared/breadcrumbs", links: [["Accueil", root_path], ["Campagnes", admin_campaigns_path], [campaign_title(@campaign), admin_campaign_path(@campaign)]], current_page_label: "Prévisualisation des mails de lancement"
  %h1= title

  = render "shared/campaigns/mail_previews_content", campaign: @campaign, routes_prefix: :admin