config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ## -----
  ## DEVISE
  ## -----

  devise_for :admin_users, skip: [:registrations]
  authenticate :admin_user do
    mount GoodJob::Engine => "/good_job"
  end

  devise_for :users, skip: [:registrations], controllers: {
    sessions: "users/sessions"
  }
  devise_scope :user do
    # we've disabled registrations to avoid sign ups, but we still want editable users
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"

    get "magic-authentication", to: "users/sessions#redirect_from_magic_token"
    namespace :users, as: :user do
      resource :session, only: %i[new create destroy]
      resources :session_codes, only: %i[new create]
      resource :unsubscribe, only: %i[new create]
    end
  end

  devise_for :conservateurs, only: %i[sessions passwords]
  devise_scope :conservateur do
    # we've disabled registrations to avoid sign ups, but we still want editable conservateurs
    get "conservateurs/edit" => "devise/registrations#edit", :as => "edit_conservateur_registration"
  end

  devise_for :recenseurs, only: %i[sessions], controllers: {
    sessions: "recenseurs/sessions"
  }
  devise_scope :recenseur do
    namespace :recenseurs, as: :recenseur do
      resource :session, only: %i[new create destroy]
      resources :session_codes, only: %i[new create]
      resource  :optout, only: :destroy do
        get "(:token)", action: :new, as: :new
      end
      resource :registration, only: [:show, :edit, :update, :destroy]
    end
  end

  direct :annuaire_service_public do |commune|
    if commune.is_a? Commune
      "https://www.service-public.fr/particuliers/recherche?keyword=mairie+#{commune.nom}+#{commune.departement.nom}"
    else
      "https://lannuaire.service-public.fr/navigation/mairie"
    end
  end

  ## ------
  ## PUBLIC
  ## ------

  root "pages#home"
  controller :pages do
    get :stats
    get :conditions
    get :mentions_legales
    get :confidentialite
    get "comment-ca-marche", action: :aide, as: :aide
    get "guide-de-recensement", action: :guide, as: :guide
    get :pdf, to: redirect("guide-de-recensement")
    get :admin
    get :plan
    get :declaration_accessibilite
    get :schema_pluriannuel_accessibilite
    get :accueil_conservateurs
  end
  get "campaigns.ics", to: "pages#campaigns_ics", as: :campaigns_ics
  resources :fiches, only: %i[index show]
  get "/presse", to: "presse#index", as: :presse
  get "/presse/:id", to: "presse#show", as: :article_presse
  resources :survey_votes, only: %w[new create]

  resources :communes, only: :show
  resources :objets, only: [:index, :show]
  resources :contenus, only: %i[show], controller: "content_blobs", as: "content_blobs"

  ## --------
  ## COMMUNES
  ## --------

  resources :communes, module: :communes, only: [] do
    controller :pages do
      get :premiere_visite
    end
    resource :completion, only: %i[new create show]
    resources :objets, only: %i[index show] do
      resources :recensements, only: %i[create edit update destroy] do
        resources :photos, only: %i[create destroy], controller: "recensement_photos"
      end
    end
    resource :dossier, only: [:show]
    resources :campaign_recipients, only: [:update]
    resources :messages, only: %i[index new create] do
      resources :email_attachments, only: [:show]
    end
    resource :user, only: [:update]
    resources :recenseurs, only: [:index, :create, :show] do
      resources :access, only: [:update, :destroy], as: :recenseur_access, controller: :recenseur_accesses
    end
  end

  ## --------
  ## RECENSEURS
  ## --------

  namespace :recenseurs do
    controller :pages do
      get :premiere_visite
      put :premiere_visite, action: :after_premiere_visite, as: :after_premiere_visite
    end
    resources :communes, only: %i[index show] do
      resource :completion, only: %i[new create show]
      resources :objets, only: %i[index show] do
        resources :recensements, only: %i[create edit update destroy] do
          resources :photos, only: %i[create destroy], controller: "recensement_photos"
        end
      end
      resource :dossier, only: [:show]
      # resources :campaign_recipients, only: [:update]
      resources :messages, only: %i[index new create] do
        resources :email_attachments, only: [:show]
      end
    end
  end

  ## -------------
  ## CONSERVATEURS
  ## -------------

  namespace :conservateurs do
    resources :departements, only: %i[index show] do
      get :activite, on: :collection, action: :activite_des_departements
      get :carte, on: :member
      get :activite, on: :member
      resources :campaigns, only: %i[new]
    end
    resources :communes, only: [:show] do
      collection do
        post :autocomplete
      end
      resources :messages, only: %i[index new create] do
        resources :email_attachments, only: [:show]
      end
      resource :dossier, only: :show
      get :historique, as: :historique, to: "dossiers#historique"
      resources :bordereaux, only: %i[index create show]
      resource :deleted_recensements, only: [:show]
    end
    resources :objets, only: [] do
      resources :recensements, only: [] do
        resource :analyse, only: %i[edit update]
      end
    end
    resources :dossiers, only: [] do
      resource :accept, only: %i[new create update destroy]
    end
    resources :campaigns, except: %i[new index] do
      get :edit_recipients
      patch :update_recipients
      patch :update_status
      get :mail_previews
      resources :recipients, controller: "campaign_recipients", only: :update do
        get :mail_preview
      end
    end
    resources :recenseurs do
      resources :accesses, only: [:new, :create, :update], as: :recenseur_access, controller: :recenseur_accesses
    end
    resource :conservateur, only: [:update]
    resources :visits, only: [:index]
    resources :fiches, only: :index
    resources :attachments, only: %i[create update destroy]
  end

  ## -----
  ## ADMIN
  ## -----

  namespace :admin do
    resources :communes, only: %i[index show] do
      post :session_code, on: :member
    end
    resources :conservateurs do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
    end
    resources :dossiers, only: [:show]
    resources :users, only: %i[] do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
    end
    resources :recenseurs do
      post :impersonate, on: :member
      delete :stop_impersonating, on: :member
      post :toggle_impersonate_mode, on: :collection
      resources :accesses, only: [:show, :new, :create, :update], as: :recenseur_access, controller: :recenseur_accesses
    end
    get "/session_codes(/:offset)", to: "session_codes#index", as: :session_codes
    resources :campaigns do
      get :edit_recipients
      patch :update_recipients
      patch :update_status
      get :mail_previews
      if Rails.configuration.x.environment_specific_name != "production"
        post :force_start
        post :force_step_up
      end
      resources :recipients, controller: "campaign_recipients", only: :update do
        get :mail_preview
      end
      resources :emails, controller: "campaign_emails", only: [] do
        get :redirect_to_sib_preview
      end
    end
    resources :admin_comments, only: %i[create destroy], controller: "comments"
    namespace :exports do
      resources :memoire, except: :edit
      controller :mpp do
        get :deplaces
        get :manquants
      end
    end
    resources :attachments, only: [:destroy] do
      post :rotate
      put :exportable
    end
    resources :messages, only: [:create] do
      resources :email_attachments, only: [:show]
    end
    resources :mail_previews, only: [:index] do
      get "/:mailer/:email", on: :collection, action: :show, as: :preview
    end
    resources :admin_users
  end

  # -----
  # API
  # -----

  namespace :api do
    namespace :v1 do
      resources :inbound_emails, only: [:create]
    end
  end

  # --------------
  # HEALTH & DEBUG
  # --------------

  get "health/raise_on_purpose", to: "health#raise_on_purpose"
  get "health/js_error", to: "health#js_error"
  get "health/slow_image", to: "health#slow_image" if Rails.env.development?
end

# rubocop:enable Metrics/BlockLength

app/views/shared/_breadcrumbs.html.erb
<nav role="navigation" class="fr-breadcrumb co-print-invisible" aria-label="vous êtes ici :">
  <button class="fr-breadcrumb__button" aria-expanded="false" aria-controls="breadcrumb-1">Voir le fil d’Ariane</button>
  <div class="fr-collapse" id="breadcrumb-1">
    <ol class="fr-breadcrumb__list">
      <% local_assigns[:links].map do |label, path| %>
        <li>
          <%= link_to truncate(label, length: 25), path, class: "fr-breadcrumb__link", title: label.size > 25 ? label : nil %>
        </li>
      <% end %>
      <li>
        <a class="fr-breadcrumb__link" aria-current="page" <%= "title=#{current_page_label}" if current_page_label.to_s.size > 25 %>>
          <%= truncate(current_page_label, length: 25) %>
        </a>
      </li>
    </ol>
  </div>
</nav>

app/views/shared/_campaign_recipient_opt_out_form.html.erb
<% if recipient.errors.any? %>
  <div class="fr-alert fr-alert--error fr-mb-4w">
    <p>
      <ul>
        <% recipient.errors.attribute_names.each do |attribute| %>
          <li><%= recipient.errors.messages_for(attribute).first %></li>
        <% end %>
      </ul>
    </p>
  </div>
<% end %>

<div class="fr-grid-row fr-mb-8w">
  <div class="fr-col-md-6">
    <%= form_for(
      recipient,
      builder: FormBuilderDsfr,
      data: { controller: "dependent-fields" },
      url: url,
      method: :patch
    ) do |f| %>
      <div class="fr-checkbox-group">
        <%= f.check_box(
          :opt_out,
          data: {
            action: "change->dependent-fields#refresh",
            "dependent-fields-target": "toggler"
          },
          autocomplete: "off"
        ) %>
        <%= f.label :opt_out, "Ne plus envoyer de mails de cette campagne ⛔️" %>
      </div>
      <div class="fr-input-group">
        <%= f.label :opt_out_reason, "Raison" %>
        <%= f.select(
          :opt_out_reason,
          CampaignRecipient::OPT_OUT_REASONS.map do |key|
            [t("activerecord.attributes.campaign_recipient.opt_out_reason.#{key}"), key]
          end,
          {},
          data: {
            "dependent-fields-target": "dependent"
          },
          autocomplete: "off"
        ) %>
      </div>
      <%= f.submit "Sauvegarder" %>
    <% end %>
  </div>
</div>

app/views/shared/_card_photo.html.haml
- photo ||= PhotoPresenter.new(url: "illustrations/photo-manquante.png", description: "Photo manquante")

.fr-card__img
  = image_tag(photo.url, class: "fr-responsive-img co-object-fit-contain", alt: photo.alt)
  = yield

app/views/shared/_cta_voir_objets.html.erb
<% if current_user&.commune %>
  <%= link_to "Voir les objets de #{current_user.commune.nom}" , commune_objets_path(current_user.commune), class: "fr-btn" %>
<% else %>
  <%= link_to "Voir les objets de ma commune" , new_user_session_code_path, class: "fr-btn" %>
<% end %>

app/views/shared/_dossier_rapport.html.haml
-# local_assigns: (:rapport)

%div{ data: { controller: "print" } }
  .fr-grid-row
    .fr-col-md-10
      %h1 Examen du recensement
    .fr-col-md-2.co-text--right.co-print-hide
      = link_to "Imprimer",
        commune_dossier_path(@commune, view: :print),
        class: "fr-btn fr-btn--secondary fr-btn--icon-right fr-icon-printer-line",
        data: { action: "click->print#print" }

  .co-flex.co-flex--align-items-center.co-flex--gap-1rem.fr-mb-2w
    %div
      %h2.fr-mb-0= @commune
    - if current_conservateur
      = dossier_visit_badge(rapport.dossier)

  .fr-grid-row.fr-mt-4w.co-break-after-page
    .fr-col-md-8
      %div
        Dossier de recensement examiné le #{l(rapport.accepted_at.to_date)} par #{rapport.conservateur}
        (#{link_to(rapport.conservateur.email, "mailto:#{rapport.conservateur.email}", data: { turbo_frame: "_top" })})

      .fr-mt-4w
        = render DsfrComponent::AccordionComponent.new do |accordion|
          - accordion.section title: "Afficher la table des matières",
            expanded: local_assigns[:toc_expanded] do
            %ul
              %li
                %a{href: "#commentaires"} Commentaires
              %li
                %a{href: "#fiches"} Vue des objets regroupés par fiche conseil
                %ul
                  - rapport.each_fiche_item do |index:, fiche:, recensements:|
                    %li
                      %a{href: "#fiche-#{fiche.id}"}
                        Fiche #{index} · #{fiche.title} (#{recensements.count} objets)
              %li
                %a{href: "#objets"} Vue détaillée objet par objet
                %ul
                  - rapport.each_recensement_item do |objet:, index:, **|
                    %li
                      %a{href: "##{objet.palissy_REF}"}
                        Objet #{index} · #{objet.nom}

  .fr-grid-row.fr-mt-4w.co-break-after-page#commentaires
    .fr-col-md-8.co-background--light-teal.fr-p-4w.co-print-no-padding
      %h3.fr-text--md.fr-mb-0 Commentaires de la commune
      .fr-mb-4w= rapport.notes_commune.presence || "Aucun commentaire"
      %h3.fr-text--md.fr-mb-0 Commentaires du conservateur
      = rapport.notes_conservateur.presence || "Aucun commentaire"

  - if rapport.fiches.any?
    %h4.fr-mt-4w#fiches Vue des objets regroupés par fiche conseil
    .co-break-after-page.co-break-after-auto--last-child
      - rapport.each_fiche_item do |fiche:, recensements:, index:|
        %div.co-break-inside-avoid{id: "fiche-#{fiche.id}"}
          %h5 Fiche #{index} · #{fiche.title}
          .fr-mb-2w
            Le conservateur vous a recommandé la lecture de la fiche conseil suivante pour
            - if recensements.count == 1
              cet objet
            - else
              ces #{recensements.count} objets
          .co-print-hide.fr-mb-2w
            = link_to "Voir la fiche conseil \"#{fiche.title}\"",
              fiche_path(fiche.id),
              data: { turbo_frame: "_top" },
              class: "fr-btn fr-btn--secondary fr-btn--icon-right fr-icon-arrow-right-line"

          .co-print-hide
            .fr-mb-4w.fr-grid-row.fr-grid-row--gutters
              - recensements.each do |recensement|
                .fr-col-md-3
                  - objet = recensement.objet
                  = render ::ObjetCardComponent.new objet,
                    commune: @commune,
                    recensement: recensement,
                    path: current_user ? commune_objet_path(@commune, objet) : objet_path(objet),
                    main_photo_origin: :recensement,
                    link_html_attributes: { data: { turbo_frame: "_top" } }

          .hide.co-print-display.fr-mb-4w
            - recensements.each_slice(4) do |recensements|
              .fr-grid-row.fr-grid-row--gutters.co-flex--align-items-center
                - recensements.each do |recensement|
                  - objet = recensement.objet
                  .fr-col-sm-4
                    .co-rapport-photo
                      - if recensement.photos_count&.positive?
                        = vite_or_raw_image_tag recensement.photos.first.variant(:medium), alt: "© Licence ouverte"
                    #{objet.nom} (#{objet.palissy_EDIF}) ·
                    %span.fr-text--sm #{objet.palissy_REF}

  %h4.fr-mt-8w#objets.co-break-after-avoid Vue détaillée objet par objet
  - rapport.each_recensement_item do |**recensement_item|
    = render "shared/rapport/recensement", **recensement_item

app/views/shared/_dossier_rapport.slim
h1 Rapport de recensement
h2
  => dossier.commune
  - if dossier.scope_edifice?
    ' -
    = edifice_nom(dossier.edifice).html_safe

p
  - if dossier.author_user?
    ' Dossier de recensement analysé le #{l(dossier.accepted_at.to_date)}
  - elsif dossier.author_conservateur?
    ' Dossier de recensement envoyé le #{l(dossier.accepted_at.to_date)}
  | par #{dossier.conservateur}
  | (
  a[href="mailto:#{dossier.conservateur.email}"]= dossier.conservateur.email
  | )


h4 Table des matières
ul.fr-mb-8w
  li
    a href="#commentaires" Commentaires
  - dossier.recensements.each_with_index do |recensement, index|
    li
      a href=recensement.objet.palissy_REF
        | #{index + 1} - #{recensement.objet.nom}

- if dossier.author_user?
  h4= t('activerecord.attributes.dossier.notes_commune')
  p= blockquote(dossier.notes_commune.presence || "Aucun commentaire")

h4= t('activerecord.attributes.dossier.notes_conservateur')
p= blockquote(dossier.notes_conservateur.presence || "Aucun commentaire")

- dossier.recensements.each_with_index do |recensement, index|
  - presenter = RecensementPresenter.new(recensement)
  .fr-my-8w id=recensement.objet.palissy_REF
    h4 #{index + 1} - #{recensement.objet.nom}
    .fr-grid-row
      .fr-col-md-6

        p.fr-text--sm
          - if current_user
            => link_to "voir lʼobjet", commune_objet_path(dossier.commune, recensement.objet)
          - elsif current_conservateur
            => link_to "voir lʼobjet", objet_path(recensement.objet)
          ' ·
          | Référence POP Palissy : #{recensement.objet.palissy_REF}

        - if recensement.missing_photos?
          span.fr-badge.fr-badge--sm.fr-badge--warning
            = t("recensement.photos.taken_count", count: 0)

        p
          .co-text--bold
            = t("activerecord.attributes.recensement.localisation")
          = presenter.localisation

        p
          .co-text--bold
            = t("activerecord.attributes.recensement.recensable")
          = presenter.recensable

        - if recensement.recensable?
          - %i[etat_sanitaire_edifice etat_sanitaire securisation].each do |original_attribute_name|
            p
              .co-text--bold
                = t("activerecord.attributes.recensement.#{original_attribute_name}").html_safe

              = render Conservateurs::AnalyseOverrideComponent.new( \
                recensement: recensement, \
                recensement_presenter: presenter, \
                original_attribute_name: \
              )

        - if dossier.author_user?
          p
            .co-text--bold
              = t("activerecord.attributes.recensement.notes")
            = blockquote(recensement.notes.presence || "Aucun commentaire")

        p
          .co-text--bold
            = t("dossier.rapport.recensement.analyse_notes")
          = blockquote(recensement.analyse_notes.presence || "Aucun commentaire")

        - if recensement.analyse_fiches.any?
          .co-text--bold
            = t("dossier.rapport.recensement.analyse_fiches")
          ul
            - recensement.analyse_fiches.each do |fiche_key|
              li= link_to "voir la fiche #{fiche_key}", fiche_path(pdf: "fiche_#{fiche_key}")

        - if current_conservateur && recensement.analyse_actions.any?
          .co-text--bold
            = t("dossier.rapport.recensement.analyse_actions")

          ul
            - recensement.analyse_actions.each do |action|
              li= action

      .fr-col-md-6.co-flex-md-reverse-order
        - if recensement.photos.any?
          = render GalleryComponent.from_attachments( \
            recensement.photos, \
            title: t("recensement.photos.taken_count", count: recensement.photos.count) \
          )

app/views/shared/_grid_layout.html.erb
<div class="fr-grid-row fr-grid-row--gutters">
  <%= yield %>
</div>

app/views/shared/_header.haml
= dsfr_header(logo_text: "Ministère\nde la Culture".html_safe,
  title: "Collectif Objets",
  tagline: "Préservez votre patrimoine mobilier",
  html_attributes: {id: "header-navigation"}) do |c|

  - if current_conservateur
    - c.with_tool_link title: current_conservateur, path: edit_conservateur_registration_path, classes: ["fr-icon-settings-5-line"]
    - c.with_tool_link title: "Activité des communes", path: activite_conservateurs_departements_path, classes: ["fr-icon-notification-3-line"]
    - c.with_tool_link title: "Déconnexion", path: destroy_conservateur_session_path, classes: ["fr-icon-logout-box-r-line"], html_attributes: { "data-turbo-method": "DELETE" }

    - if current_conservateur.departements.count > 2
      - c.with_direct_link_simple title: "Mes départements", path: conservateurs_departements_path, active: active_nav_link?("Mes départements")
    - else
      - current_conservateur.departements.each do |departement|
        - c.with_direct_link_simple title: departement, path: conservateurs_departement_path(departement.code), active: active_nav_link?(departement.to_s)

    - c.with_direct_link_dropdown title: "Mes actions", active: active_nav_link?("Mes actions") do |dropdown|
      - dropdown.with_link title: "Déplacements prévus", path: conservateurs_visits_path
      - dropdown.with_link title: "Fiches attribuées", path: conservateurs_fiches_path

    - c.with_direct_link_simple title: "Recenseurs", path: conservateurs_recenseurs_path, active: active_nav_link?("Recenseurs")

    - c.with_direct_link_simple title: "Documentation", path: content_blob_path(:documentation_conservateur), active: active_nav_link?("Documentation")

    - c.with_search do
      = render "shared/header/header_conservateur_search"

  - elsif current_user
    - c.with_tool_link title: "Voir les objets de #{current_user.commune.nom}", path: commune_objets_path(current_user.commune), classes: ["fr-icon-eye-line"]
    - c.with_tool_link title: "Déconnexion", path: user_session_path, classes: ["fr-icon-logout-box-r-line"], html_attributes: { "data-turbo-method": "DELETE" }
    - c.with_tool_link title: "Préférences", path: edit_user_registration_path, classes: ["fr-icon-settings-5-line"]

    - c.with_direct_link_simple title: "Recensement", path: commune_objets_path(current_user.commune), active: active_nav_link?("Recensement")
    - c.with_direct_link_simple title: commune_messagerie_title(current_user.commune), path: commune_messages_path(current_user.commune), active: active_nav_link?("Messagerie")
    - c.with_direct_link_simple title: "Examen du conservateur", path: commune_dossier_path(current_user.commune), active: active_nav_link?("Examen du conservateur")
    - c.with_direct_link_simple title: "Recenseurs", path: commune_recenseurs_path(current_user.commune), active: active_nav_link?("Recenseurs")
    - c.with_direct_link_simple title: "Comment ça marche ?", path: aide_path, active: active_nav_link?("Comment ça marche ?")

    - c.with_direct_link_dropdown title: "À propos", active: active_nav_link?("À propos", "Aide en ligne", "On parle de nous", "Statistiques") do |dropdown|
      - dropdown.with_link title: "Aide en ligne", path: content_blob_path(:aide_en_ligne), active: active_nav_link?("Aide en ligne")
      - dropdown.with_link title: "On parle de nous", path: presse_path
      - dropdown.with_link title: "Statistiques", path: stats_path

  - elsif current_recenseur
    - c.with_tool_link title: "Préférences", path: recenseur_registration_path, classes: ["fr-icon-settings-5-line"]
    - c.with_tool_link title: "Déconnexion", path: recenseur_session_path, classes: ["fr-icon-logout-box-r-line"], html_attributes: { "data-turbo-method": :delete }

    - if current_recenseur.communes.count == 1
      - commune = current_recenseur.communes.first
      - c.with_direct_link_simple title: commune, path: recenseurs_commune_path(commune), active: active_nav_link?("Communes")
      - c.with_direct_link_simple title: "Recensement", path: recenseurs_commune_objets_path(commune), active: active_nav_link?("Recensement")
      - c.with_direct_link_simple title: "Examen du conservateur", path: recenseurs_commune_dossier_path(commune), active: active_nav_link?("Examen du conservateur") if policy(commune).dossier?
    - else
      - c.with_direct_link_simple title: "Communes", path: recenseurs_communes_path, active: active_nav_link?("Communes")
      - c.with_direct_link_simple title: "Recensement", path: recenseurs_commune_path(@commune), active: active_nav_link?("Recensement") if @commune
      - c.with_direct_link_simple title: "Examen du conservateur", path: recenseurs_commune_dossier_path(@commune), active: active_nav_link?("Examen du conservateur") if @commune && policy(@commune).dossier?

    - c.with_direct_link_simple title: "Comment ça marche ?", path: content_blob_path(:aide_en_ligne), active: active_nav_link?("Aide en ligne")

    - c.with_direct_link_dropdown title: "À propos", active: active_nav_link?("À propos", "On parle de nous", "Statistiques") do |dropdown|
      - dropdown.with_link title: "On parle de nous", path: presse_path
      - dropdown.with_link title: "Statistiques", path: stats_path

  - elsif current_admin_user
    - c.with_tool_link title: "#{current_admin_user} (Admin)", path: admin_path, classes: ["fr-icon-admin-line"]
    - c.with_tool_link title: "Déconnexion", path: destroy_admin_user_session_path, classes: ["fr-icon-logout-box-r-line"], html_attributes: { "data-turbo-method": "DELETE" }
    - c.with_direct_link_simple title: "Administration", path: admin_path, active: active_nav_link?("Administration")
    - c.with_direct_link_simple title: "Communes", path: admin_communes_path, active: active_nav_link?("Communes")
    - c.with_direct_link_simple title: "Conservateurs", path: admin_conservateurs_path, active: active_nav_link?("Conservateurs")
    - c.with_direct_link_simple title: "Recenseurs", path: admin_recenseurs_path, active: active_nav_link?("Recenseurs")
    - c.with_direct_link_simple title: "Campagnes", path: admin_campaigns_path, active: active_nav_link?("Campagnes")
    - c.with_direct_link_simple title: "CMS", path: "https://collectif-objets-cms.netlify.app/", html_attributes: { target: "_blank", rel: "noopener" }

  - else
    - c.with_tool_link title: "Connexion commune", path: new_user_session_code_path, classes: ["fr-icon-user-line"]
    - c.with_tool_link title: "Connexion conservateur", path: new_conservateur_session_path, classes: ["fr-icon-user-star-line"]

    - c.with_direct_link_simple title: "Comment ça marche ?", path: aide_path, active: active_nav_link?("Comment ça marche ?")
    - c.with_direct_link_simple title: "On parle de nous", path: presse_path, active: active_nav_link?("On parle de nous")
    - c.with_direct_link_simple title: "Statistiques", path: stats_path, active: active_nav_link?("Statistiques")
    - c.with_direct_link_simple title: "Je suis conservateur", path: accueil_conservateurs_path, active: active_nav_link?("Je suis conservateur")

app/views/shared/_messages.html.haml
.co-max-height-40vh.co-overflow-auto.co-background--light-grey.co-border.fr-p-2w#messages-list{ data: { controller: "messages", messages: { target: "list" } } }
  - if messages.empty?
    %p.co-text--italic#empty-message Aucun message pour le moment
  - else
    = render MessageComponent.with_collection(messages, viewed_by: )

app/views/shared/_pagy_prev_next.html.erb
<% link = pagy_link_proc(pagy) -%>
<div class="co-flex co-flex--space-between co-flex--align-items-center co-flex--wrap co-flex--gap-05rem">
  <% if pagy.page == 1 %>
    <span role="button" aria-disabled="true" class="fr-btn fr-btn--tertiary-no-outline">Résultats précédents</span>
  <% else %>
    <%== link.call(pagy.prev, "Résultats précédents", 'class="fr-btn fr-btn--tertiary"') %>
  <% end %>

  <% if !pagy.next %>
    <span role="button" aria-disabled="true" class="fr-btn fr-btn--tertiary-no-outline">Résultats suivants</span>
  <% else %>
    <%== link.call(pagy.next, "Résultats suivants", 'class="fr-btn fr-btn--tertiary"') %>
  <% end %>
</div>

app/views/shared/_picture_tag.html.erb
<picture>
  <source
    type="image/webp"
    srcset="<%= asset_path "#{filename_without_extension}.webp" %>"
  >
  <source
    type="image/png"
    srcset="<%= asset_path "#{filename_without_extension}.png" %>"
  >
  <img
    src="<%= asset_path "#{filename_without_extension}.png" %>"
    alt="<%= alt %>"
    class="<%= local_assigns[:img_class] %>"
  >
</picture>

app/views/shared/_tracking_scripts.html.erb
<input id="current-user-email" type="hidden" value="<%= current_user&.email %>">

<% if Rails.env.production? && !Rails.application.staging? %>
  <%= vite_javascript_tag "matomo_tracking" %>
<% end %>